version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install --force
      - aws s3 cp s3://helping-hand-resources/.env .

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'